name: ccaguaviva
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.2+3

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  firebase_analytics: ^9.1.5
  firebase_core: ^1.14.1
  firebase_remote_config: ^2.0.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.0.1+1
  url_launcher: ^6.0.18
  webview_flutter: ^3.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/icon/
    - assets/splash/

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
  image_path_ios: "assets/icon/Icon_runner.png"
  image_path_android: "assets/icon/icon.png"
  adaptive_icon_background: "assets/icon/icon_round.png"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"

flutter_native_splash:
  android: true
  ios: true
  web: true

  fullscreen: true

  color: "#F2F2F7"
  # background_image: "assets/background.png"
  image: assets/splash/dark.png

  color_dark: "#000000"
  # background_image_dark: "assets/dark-background.png"
  image_dark: assets/splash/light.png
  # android12: true
