// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlg_4REfX8wem25q6veMmnNYWC4ls0AIM',
    appId: '1:822124063540:web:b738688d8ba7a4cc275361',
    messagingSenderId: '822124063540',
    projectId: 'ccaguaviva-7b357',
    authDomain: 'ccaguaviva-7b357.firebaseapp.com',
    storageBucket: 'ccaguaviva-7b357.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxrbW6IkV2FLl6IvOIDkIWXU8UcjpEMKc',
    appId: '1:822124063540:android:0a783c016c630bff275361',
    messagingSenderId: '822124063540',
    projectId: 'ccaguaviva-7b357',
    storageBucket: 'ccaguaviva-7b357.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVT5j5qHHT8I4AMRHpZFHxvubCmZKqf6A',
    appId: '1:822124063540:ios:c7414365aa375908275361',
    messagingSenderId: '822124063540',
    projectId: 'ccaguaviva-7b357',
    storageBucket: 'ccaguaviva-7b357.appspot.com',
    iosClientId:
        '822124063540-q8pd4osbsj0cm59csr18o1dm6o90eb7j.apps.googleusercontent.com',
    iosBundleId: 'aulavirtual.ccaguaviva.app',
  );
}
